[features]
seeds = false
skip-lint = false

[programs.localnet]
gent_staking = "your_program_id"

[programs.devnet]
gent_staking = "your_program_id"

[programs.mainnet]
gent_staking = "your_program_id"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "anchor deploy"
build = "anchor build"
start = "anchor start"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"